apiVersion: v1
kind: Secret
metadata:
  name: credentials
  labels:
{{ include "photoprism.labels" . | indent 4 }}
stringData:
{{- if eq .Values.database.driver "internal" }}
  dsn: 'root:photoprism@tcp(localhost:4000)/photoprism?parseTime=true'
{{ else }}
  dsn: '{{ .Values.database.user }}:{{ .Values.database.password }}@tcp({{ .Values.database.host }}:{{ .Values.database.port }})/{{ .Values.database.name }}?parseTime=true'
{{ end }}